### PR TITLE
Remove json file generating/posting in indexing (Ready for review)

### PR DESCRIPTION
**Pull request by kshefchek**
See background ticket: https://github.com/SciGraph/golr-loader/issues/32

This PR replaces portions of code that convert Neo4J results to JSON, with code that converts Neo4J results to solr input doc objects and then adds them using SolrJ.

Note that the tests are now broken, I will fix or write new ones.  To build:
mvn clean install -Dmaven.test.skip

### CODE REVIEW

**Comment by kltm** [comment]
@kshefchek Would you know what version of Solr you're using in production?

**Comment by kshefchek** [comment]
@kltm yes we are using 6.2.1

**Comment by kltm** [comment]
Okay, it's coming back to me now--wanting to make sure that no incompatibilities creep in, then remembering that we already tested for that.

It all looks pretty sane to me, it seems more of a conversion than a complete rewrite (not to underplay all the work in there).
The only thing that comes to mind would be that it might be nice to be able to get at the batching size for experimenting without recompiling.

**Comment by kshefchek** [comment]
No you are right - it is straight conversion and was not much work.  I can make batch size a cmd line arg if that makes sense.

**Comment by cmungall** [comment]
Looks good

**Comment by kshefchek** [comment]
great! I'll test this branch to index our three cores with our dev scigraph, fix tests, and update the docs.

**Comment by kshefchek** [comment]
Batch size notes:
1 million: GC overhead limit
100k: SocketException: broken pipe
10k:  SocketException: broken pipe
1k: No exceptions

For now going with 1k batches, it may be worth catching the socket exception and examining the documents to see if one contains an excessively large evidence graph.

**Pull request merged**
